---
- name: Callepuzzle Hetznet cloud
  hosts: all
  become: true
  become_method: su

  collections:
    - nginxinc.nginx_core
  pre_tasks:
    - name: Install python-setuptools
      apt:
        name: python-setuptools
      tags:
        - nextcloud

  roles:
    - { role: nextcloud, tags: [ 'nextcloud' ] }
    - { role: nginx, tags: [ 'nginx' ] }
    - { role: nginx_config, tags: [ 'nginx' ] }

  tasks:
    - name: Copy dhparam
      copy:
        src: templates/dhparam
        dest: /etc/nginx/dhparam
      tags:
        - nginx
