---
- name: Callepuzzle Hetznet cloud
  hosts: nextcloud

  collections:
    - nginxinc.nginx_core

  pre_tasks:
    - name: Install python-setuptools
      apt:
        name: python-setuptools
      tags:
        - nextcloud

  roles:
    - { role: nextcloud, tags: [ 'nextcloud' ] }
    - { role: nginx, tags: [ 'nginx' ] }
    - { role: nginx_config, tags: [ 'nginx' ] }
